package com.matthewtole.androidrise.lib.enums;

public enum UpdateType {
	WORKER_SELECTED, WORKER_UNSELECTED, WORKER_MOVED, WORKER_ADDED, WORKER_JUMP,
	TILE_ADDED,
	TOWER_REDUCED, TOWER_DEMOLISHED, TOWER_CREATED, TOWER_BUILT,
	SACRIFICE_REMOVE, SACRIFICE_ADD,
	MOVE_MADE, TURN_FINISHED
};
